### ISSUE TITLE
JSON Github Pages example

### ISSUE THREAD

**Issue by davelab6** [cben/sandbox#11]
I came across this repo in https://stackoverflow.com/questions/39199042/serve-json-data-from-github-pages - I wonder if you could tell me why https://davelab6.github.io is not loading :)

**Comment by cben** [comment]
Hi, sorry for delayed response.

Something does load but I guess there should be a list of fonts.
I see 2 failed requests in Chromium network tab:
https://davelab6.github.io/metadata/fonts — "canceled"
http://davelab6.github.io/metadata/fonts/ — "blocked as mixed content"

If the 2nd request is initiated directly, just fix http:// to be https://.
But while I'm not sure what "cancelled" means, I suspect the 2nd request is just a result of redirect GitHub pages returns to 1st request.
It's a long-standing annoyance [1] that when requesting a directory omitting the trailing slash, Pages redirects to url with trailing slash but over insecure http://.  This kinda works but in this situation is blocked by browser.
The fix is simply appending trailing slash in original URL — https://davelab6.github.io/metadata/fonts/ — should avoid the problematic redirect.

[1] https://github.com/isaacs/github/issues/289#issuecomment-374870588
